services:
  taskflow-api:
    image: taskflow-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=taskflow-db;Database=TaskFlowDB;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      taskflow-db:
        condition: service_healthy

  taskflow-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD} 
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${SA_PASSWORD}' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s